---
- name: Create Jenkins users
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:
    - name: Start Jenkins
      service:
        name: jenkins
        state: started

    - name: Jenkins skip startUp wizard
      lineinfile: dest=/etc/sysconfig/jenkins
        regexp='^JENKINS_JAVA_OPTIONS='
        line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      register: result_skip_startup_wizard

    - name: Restart Jenkins after disable startUp wizard
      service:
        name: jenkins
        state: restarted

    - name: Wait for Jenkins to start up
      uri:
        url: http://localhost:8080
        status_code: 200
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 240
      delay: 5
      until: >
        'status' in jenkins_service_status and
        jenkins_service_status['status'] == 200

    - name: Create custom init scripts directory
      file:
        path: "{{ jenkins.jenkins_home }}/init.groovy.d"
        state: directory
        owner: "{{ jenkins.jenkins_process_user }}"
        group: "{{ jenkins.jenkins_process_group }}"
        mode: 0775

    - name: Configure default Jenkins users
      template:
        src: ../../templates/jenkins-basic-security.groovy.j2
        dest: "{{ jenkins.jenkins_home }}/init.groovy.d/jenkins-basic-security.groovy"
        owner: "{{ jenkins.jenkins_process_user }}"
        group: "{{ jenkins.jenkins_process_group }}"
        mode: 0775
      register: jenkins_user_config

    - name: Restart Jenkins after creating Jenkins users
      service:
        name: jenkins
        state: restarted

    - name: Wait for Jenkins to start up
      uri:
        url: http://localhost:8080
        status_code: 200
        timeout: 5
      register: jenkins_service_status
      # Keep trying for 5 mins in 5 sec intervals
      retries: 240
      delay: 5
      until: >
        'status' in jenkins_service_status and
        jenkins_service_status['status'] == 200
