---
jenkins:
  plugins:
    artifactory:
      enabled: yes
      version: "3.6.1"
    aws-java-sdk:
      enabled: yes
      version: "1.11.723"
    aws-credentials:
      enabled: yes
      version: "1.28"
    sonar:
      enabled: yes
      version: "2.11"
    aws-parameter-store:
      enabled: yes
      version: "1.2.2"
    matrix-auth:
      enabled: yes
      version: "2.5"
    docker-workflow:
      enabled: yes
      version: "1.21"
    checkmarx:
      enabled: yes
      version: "8.90.4"
    credentials:
      enabled: yes
      version: "2.3.5"
    extended-choice-parameter:
      enabled: yes
      version: "0.78"
    git-server:
      enabled: yes
      version: "1.9"
    workflow-cps-global-lib:
      enabled: yes
      version: "2.15"
    jquery:
      enabled: yes
      version: "1.12.4-1"
    structs:
      enabled: yes
      version: "1.20"
    uno-choice:
      enabled: yes
      version: "2.2.1"
    ssh-slaves:
      enabled: yes
      version: "1.31.0"
    workflow-api:
      enabled: yes
      version: "2.38"
    lockable-resources:
      enabled: yes
      version: "2.7"
    display-url-api:
      enabled: yes
      version: "2.3.2"
    ant:
      enabled: yes
      version: "1.10"
    project-inheritance:
      enabled: yes
      version: "19.08.02"
    github-branch-source:
      enabled: yes
      version: "2.5.8"
    github-oauth:
      enabled: yes
      version: "0.33"
    github-organization-folder:
      enabled: yes
      version: "1.6"
    jsch:
      enabled: yes
      version: "0.1.55.1"
    pipeline-model-definition:
      enabled: yes
      version: "1.5.0"
    cloudbees-folder:
      enabled: yes
      version: "6.10.0"
    apache-httpcomponents-client-4-api:
      enabled: yes
      version: "4.5.10-2.0"
    pipeline-utility-steps:
      enabled: yes
      version: "2.3.1"
    hidden-parameter:
      enabled: yes
      version: "0.0.4"
    htmlpublisher:
      enabled: yes
      version: "1.22"
    subversion:
      enabled: yes
      version: "2.12.2"
    maven-plugin:
      enabled: yes
      version: "3.4"
    configuration-as-code:
      enabled: yes
      version: "1.42"
    support-core:
      enabled: yes
      version: "2.65"
    pipeline-stage-view:
      enabled: yes
      version: "2.12"
    git:
      enabled: yes
      version: "4.0.0"
    ansible:
      enabled: yes
      version: "1.0"
    timestamper:
      enabled: yes
      version: "1.10"
    bouncycastle-api:
      enabled: yes
      version: "2.18"
    ldap:
      enabled: yes
      version: "1.21"
    git-client:
      enabled: yes
      version: "3.0.0"
    resource-disposer:
      enabled: yes
      version: "0.14"
    token-macro:
      enabled: yes
      version: "2.10"
    windows-slaves:
      enabled: yes
      version: "1.5"
    command-launcher:
      enabled: yes
      version: "1.4"
    ssh-credentials:
      enabled: yes
      version: "1.18"
    variant:
      enabled: yes
      version: "1.3"
    promoted-builds:
      enabled: yes
      version: "3.5"
    credentials-binding:
      enabled: yes
      version: "1.20"
    dashboard-view:
      enabled: yes
      version: "2.12"
    icon-shim:
      enabled: yes
      version: "2.0.3"
    ivy:
      enabled: yes
      version: "2.1"
    branch-api:
      enabled: yes
      version: "2.5.5"
    job-dsl:
      enabled: yes
      version: "1.76"
    metrics:
      enabled: yes
      version: "4.0.2.6"
    antisamy-markup-formatter:
      enabled: yes
      version: "1.6"
    script-security:
      enabled: yes
      version: "1.68"
    durable-task:
      enabled: yes
      version: "1.33"
    workflow-durable-task-step:
      enabled: yes
      version: "2.35"
    vsphere-cloud:
      enabled: yes
      version: "2.21"
    pipeline-stage-tags-metadata:
      enabled: yes
      version: "1.5.0"
    workflow-step-api:
      enabled: yes
      version: "2.21"
    email-ext:
      enabled: yes
      version: "2.68"
    pam-auth:
      enabled: yes
      version: "1.6"
    gradle:
      enabled: yes
      version: "1.35"
    pipeline-model-api:
      enabled: yes
      version: "1.5.0"
    workflow-cps:
      enabled: yes
      version: "2.78"
    pipeline-model-extensions:
      enabled: yes
      version: "1.5.0"
    scm-api:
      enabled: yes
      version: "2.6.3"
    pipeline-rest-api:
      enabled: yes
      version: "2.12"
    pipeline-restful-api:
      enabled: yes
      version: "0.6"
    mailer:
      enabled: yes
      version: "1.29"
    parameterized-trigger:
      enabled: yes
      version: "2.36"
    jdk-tool:
      enabled: yes
      version: "1.4"
    github:
      enabled: yes
      version: "1.29.5"
    h2-api:
      enabled: yes
      version: "1.4.199"
    workflow-job:
      enabled: yes
      version: "2.36"
    jackson2-api:
      enabled: yes
      version: "2.11.0"
    pipeline-aggregator-view:
      enabled: yes
      version: "1.9"
    pipeline-aws:
      enabled: yes
      version: "1.41"
    pipeline-config-history:
      enabled: yes
      version: "1.6"
    pipeline-deploymon:
      enabled: yes
      version: "1.0"
    pipeline-giphy-api:
      enabled: yes
      version: "2.0.1"
    pipeline-github:
      enabled: yes
      version: "2.5"
    pipeline-githubnotify-step:
      enabled: yes
      version: "1.0.5"
    pipeline-global-lib-nexus:
      enabled: yes
      version: "0.2.2"
    pipeline-maven:
      enabled: yes
      version: "3.8.2"
    pipeline-input-step:
      enabled: yes
      version: "2.11"
    pipeline-build-step:
      enabled: yes
      version: "2.10"
    mapdb-api:
      enabled: yes
      version: "1.0.9.0"
    ace-editor:
      enabled: yes
      version: "1.1"
    workflow-basic-steps:
      enabled: yes
      version: "2.18"
    async-http-client:
      enabled: yes
      version: "1.9.40.0"
    github-api:
      enabled: yes
      version: "1.95"
    git-parameter:
      enabled: yes
      version: "0.9.11"
    analysis-core:
      enabled: yes
      version: "1.96"
    node-iterator-api:
      enabled: yes
      version: "1.5.0"
    junit:
      enabled: yes
      version: "1.28"
    conditional-buildstep:
      enabled: yes
      version: "1.3.6"
    pipeline-milestone-step:
      enabled: yes
      version: "1.3.1"
    pipeline-multibranch-defaults:
      enabled: yes
      version: "2.1"
    managed-scripts:
      enabled: yes
      version: "1.4"
    naginator:
      enabled: yes
      version: "1.18"
    ws-cleanup:
      enabled: yes
      version: "0.37"
    build-timeout:
      enabled: yes
      version: "1.19"
    pipeline-model-declarative-agent:
      enabled: yes
      version: "1.1.1"
    pipeline-npm:
      enabled: yes
      version: "0.9.2"
    pipeline-timeline:
      enabled: yes
      version: "1.0.3"
    authentication-tokens:
      enabled: yes
      version: "1.3"
    handlebars:
      enabled: yes
      version: "1.1.1"
    plain-credentials:
      enabled: yes
      version: "1.5"
    workflow-support:
      enabled: yes
      version: "3.3"
    rebuild:
      enabled: yes
      version: "1.31"
    permissive-script-security:
      enabled: yes
      version: "0.5"
    javadoc:
      enabled: yes
      version: "1.5"
    workflow-multibranch:
      enabled: yes
      version: "2.21"
    multibranch-build-strategy-extension:
      enabled: yes
      version: "1.0.10"
    jquery-detached:
      enabled: yes
      version: "1.2.1"
    workflow-aggregator:
      enabled: yes
      version: "2.6"
    docker-commons:
      enabled: yes
      version: "1.15"
    workflow-scm-step:
      enabled: yes
      version: "2.9"
    pipeline-stage-step:
      enabled: yes
      version: "2.3"
    run-condition:
      enabled: yes
      version: "1.2"
    snakeyaml-api:
      enabled: yes
      version: "1.26.2"
    momentjs:
      enabled: yes
      version: "1.1.1"
    matrix-project:
      enabled: yes
      version: "1.14"
    pipeline-github-lib:
      enabled: yes
      version: "1.0"
    pipeline-graph-analysis:
      enabled: yes
      version: "1.10"
    config-file-provider:
      enabled: yes
      version: "3.6.2"
    github-pullrequest:
      enabled: yes
      version: "0.2.6"
    trilead-api:
      enabled: yes
      version: "1.0.6"
    jaxb:
      enabled: yes
      version: "2.3.0.1"
    basic-branch-build-strategies:
      enabled: yes
      version: "1.3.2"
    next-build-number:
      enabled: yes
      version: "1.6"
    ec2:
      enabled: yes
      version: "1.50.2"
    slave-setup:
      enabled: yes
      version: "1.10"
    badge:
      enabled: yes
      version: "1.8"
    groovy-postbuild:
      enabled: yes
      version: "2.5"
    gatling:
      enabled: yes
      version: "1.3.0"
    gatling-check:
      enabled: yes
      version: "1.0.0"
    text-finder:
      enabled: yes
      version: "1.12"
    Office-365-Connector:
      enabled: yes
      version: "4.12.4"
    scmskip:
      enabled: yes
      version: "1.0.3"
    splunk-devops:
      enabled: yes
      version: "1.9.4"
